prometheus:
  image: prom/prometheus:v3.2.0
  hostname: prometheus.home.arpa

alertmanager:
  image: prom/alertmanager:v0.28.0
  hostname: alertmanager.home.arpa

grafana:
  image: grafana/grafana:10.2.3
  hostname: grafana.home.arpa

# otel:
#   image: otel/opentelemetry-collector-contrib:0.137.0

alloy:
  image: ""

tempo:
  image: ""

loki:
  image: ""