---

kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-alertmanager-config"
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    global:
    route:
      receiver: example-on-call
      group_wait: 15m
      repeat_interval: 24h
      routes: []

    receivers:
    - name: example-on-call
      webhook_configs:
        - url: "https://api.example.com/triggers/YOUR-TRIGGER-ID/alert"
          http_config:
            follow_redirects: false
            authorization:
              credentials: "EXAMPLE-ON-CALL-API-KEY"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-alertmanager"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: "{{ .Chart.Name }}-alertmanager"
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:{{ .Values.alertmanager.version }}
        args:
          - "--config.file=/etc/alertmanager/config.yml"
          - "--storage.path=/alertmanager"
        ports:
          - containerPort: 9093
        resources:
            requests:
              memory: 16Mi
            limits:
              memory: 32Mi
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: "{{ .Chart.Name }}-alertmanager-config"
      - name: alertmanager
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-alertmanager"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: alertmanager
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Chart.Name }}-alertmanager"
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.alertmanager.hostname }}`)
      services:
        - kind: Service
          name: "{{ .Chart.Name }}-alertmanager"
          port: 9093
