---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Chart.Name }}-grafana-storage"
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-grafana"
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: "{{ .Chart.Name }}-grafana"
        image: grafana/grafana:{{ .Values.grafana.version }}
        volumeMounts:
          - name: "{{ .Chart.Name }}-grafana-storage"
            mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
          name: http
      volumes:
        - name: "{{ .Chart.Name }}-grafana-storage"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-grafana-storage"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 472

---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-grafana"
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Chart.Name }}-grafana"
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.grafana.hostname }}`)
      services:
        - kind: Service
          name: "{{ .Chart.Name }}-grafana"
          port: 3000
