---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "tempo.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    name: "{{ include "tempo.fullname" . }}"
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/traces

    distributor:
      log_received_spans:
        enabled: true
        
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "tempo.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "tempo.fullname" . }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "tempo.fullname" . }}"
  template:
    metadata:
      labels:
        app: "{{ include "tempo.fullname" . }}"
    spec:
      containers:
        - name: tempo
          image: "{{ .Values.tempo.image }}"
          ports:
            - http_server: 3200
            - grpc_receiver: 4317
            - http_receiver: 4318
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            limits:
              memory: 128Mi
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/
            - name: tempo-data
              mountPath: /var/tempo/
      volumes:
        - name: tempo-config
          configMap:
            defaultMode: 420
            name: "{{ include "tempo.fullname" . }}"
        - name: tempo-data
          emptyDir:
            sizeLimit: 50Mi