---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Chart.Name }}-workflows-rolebinding"
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.workflows.role }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}