apiVersion: v2
name: jdp-backend
description: JDP backend services - nfs volumes, secrets, vault, message queues 

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:

- name: traefik-crds
  version: 1.13.0
  repository: https://traefik.github.io/charts

- name: traefik
  version: 38.0.1
  repository: https://traefik.github.io/charts

- name: argo-workflows
  version: 0.46.3
  repository: https://argoproj.github.io/argo-helm

- name: argo-events
  version: 2.4.19
  repository: https://argoproj.github.io/argo-helm

- name: external-secrets
  version: 1.2.1
  repository: https://charts.external-secrets.io
