apiVersion: v2
name: jdp-backend
description: This Chart deploys jdp-backend services.

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: sealed-secrets
  version: 2.11.0
  repository: https://bitnami-labs.github.io/sealed-secrets
- name: argo-workflows
  version: 0.32.1
  repository: https://argoproj.github.io/argo-helm