---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: "{{ include "secrets.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: "{{ include "secrets.fullname" . }}"
    component: clustersecretstore
spec:
  provider:
    vault:
      server: "http://{{ include "openbao.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "{{ include "openbao.fullname" . }}"
          namespace: {{ .Release.Namespace }}
          key: "BAO_TOKEN"