---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: "{{ .Chart.Name }}-secrets"
  namespace: "{{ .Release.Namespace }}"
  labels: &labels
    app: "{{ .Chart.Name }}-secrets"
    component: clustersecretstore
spec:
  provider:
    vault:
      server: "http://{{ .Chart.Name }}-openbao"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "{{ .Chart.Name }}-openbao"
          namespace: "{{ .Release.Namespace }}"
          key: "BAO_DEV_ROOT_TOKEN_ID"