---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: nfs
  annotations:
provisioner: cluster.local/{{ .Chart.Name }}-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  archiveOnDelete: "true"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner-runner"
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:     ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs:     ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs:     ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs:     ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs:     ["create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: run-{{ .Chart.Name }}-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner-runner"
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: leader-locking-{{ .Chart.Name }}-nfs-subdir-external-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs:     ["get", "list", "watch", "create", "update", "patch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-subdir-external-provisioner
  name: leader-locking-{{ .Chart.Name }}-nfs-subdir-external-provisioner
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{ .Chart.Name }}-nfs-subdir-external-provisioner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-nfs-subdir-external-provisioner"
  labels:
    app: nfs-subdir-external-provisioner
spec:
  replicas: {{ .Values.nfs.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
  template:
    metadata:
      annotations:
      labels:
        app: nfs-subdir-external-provisioner
    spec:
      serviceAccountName: "{{ .Chart.Name }}-nfs-subdir-external-provisioner"
      securityContext: {}
      containers:
        - name: nfs-subdir-external-provisioner
          image: "registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2"
          imagePullPolicy: IfNotPresent
          securityContext: {}
          volumeMounts:
            - name: nfs-subdir-external-provisioner-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/{{ .Chart.Name }}-nfs-subdir-external-provisioner
            - name: NFS_SERVER
              value: {{ .Values.nfs.server }}
            - name: NFS_PATH
              value: {{ .Values.nfs.path }}
      volumes:
        - name: nfs-subdir-external-provisioner-root
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
