---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "openbao.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "openbao.fullname" . }}"
    component: configmap
data:
  local.json: |-
    {
      "storage": {
        "postgresql": {
          "connection_url": "postgresql://{{ .Values.openbao.database.username }}:{{ .Values.openbao.database.password }}@{{ .Values.openbao.database.host }}:{{ .Values.openbao.database.port }}/{{ .Values.openbao.database.name }}"
        }
      },
      "listener": {
        "tcp": {
          "address": "0.0.0.0:8200",
          "tls_disable": true
        }
      },
      "api_addr": "http://{{ .Values.openbao.hostname }}",
      "ui": true
    }

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ include "openbao.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "openbao.fullname" . }}"
    component: secrets
stringData:
  BAO_TOKEN: "{{ .Values.openbao.token }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "openbao.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels: &labels
    app: "{{ include "openbao.fullname" . }}"
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: openbao
        image: "{{ .Values.openbao.image }}"
        imagePullPolicy: IfNotPresent
        args:
        - server
        - -config=/openbao/config/local.json
        volumeMounts:
        - name: config
          mountPath: /openbao/config/local.json
          subPath: local.json
          readOnly: true
        ports:
        - name: api
          containerPort: 8200
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
        resources:
          limits:
            memory: 128Mi
      volumes:
      - name: config
        configMap:
          name: "{{ include "openbao.fullname" . }}"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "openbao.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "openbao.fullname" . }}"
    component: service
spec:
  selector:
    app: "{{ include "openbao.fullname" . }}"
    component: deployment
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8200

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ include "openbao.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ include "openbao.fullname" . }}"
    component: ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.openbao.hostname }}`)
      services:
        - kind: Service
          name: "{{ include "openbao.fullname" . }}"
          port: 80
