# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: "{{ .Chart.Name }}-openbao"
#   namespace: "{{ .Release.Namespace }}"
#   labels:
#     app: "{{ .Chart.Name }}-openbao"
#     component: configmap
# data:


---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Chart.Name }}-openbao"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}-openbao"
    component: secrets
stringData:
  BAO_DEV_ROOT_TOKEN_ID: "{{ .Values.openbao.token }}"
  BAO_LOCAL_CONFIG: |-
    {
      "storage":{
        "postgresql": {
          "connection_url": "postgresql://{{ .Values.openbao.database.username }}:{{ .Values.openbao.database.password }}@{{ .Values.openbao.database.host }}:{{ .Values.openbao.database.port }}/{{ .Values.openbao.database.name }}"
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-openbao"
  namespace: "{{ .Release.Namespace }}"
  labels: &labels
    app: "{{ .Chart.Name }}-openbao"
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: openbao
        image: "{{ .Values.openbao.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 8200
        envFrom:
        # - configMapRef:
        #     name: "{{ .Chart.Name }}-openbao"
        - secretRef:
            name: "{{ .Chart.Name }}-openbao"
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "1000m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-openbao"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}-openbao"
    component: service
spec:
  selector:
    app: "{{ .Chart.Name }}-openbao"
    component: deployment
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8200

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ .Chart.Name }}-openbao"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Chart.Name }}-openbao"
    component: ingress
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.openbao.hostname }}`)
      services:
        - kind: Service
          name: "{{ .Chart.Name }}-openbao"
          port: 80
